name: "m154-comp-stats"

project:
  type: website
  output-dir: _site
  resources: 
    - "handout/*"
  
website:
  title: "Computational Statistics"
  image: "images/st47s.png"
  favicon: "images/favicon.ico"
  site-url: https://m154-comp-stats.netlify.app/
  repo-url: https://github.com/hardin47/m154-comp-stats
  page-navigation: true
  navbar:
    title: "Computational Statistics"
    description: |
      Math 154, Computational Statistics, Pomona College, Fall 2025
    background: success
    foreground: secondary
    search: true
    right:
      - text: "Daily"
        href: daily.qmd
      - text: "Syllabus"
        href: syllabus.qmd
      - text: "Class Notes"
        href: notes.qmd
      - text: "Project"
        menu: 
          - text: "Project Assignment"
            href: project.qmd
          - text: "Group Roles"
            href: roles.qmd
          - text: "Rubric"
            href: rubric.qmd
          - text: "Data Sources"
            href: https://hardin47.netlify.app/courses/data-sources/
      - text: "Clicker Q"
        href: clicker_study.qmd
      - text: "GitHub"
        href: github.qmd
    logo: images/st47s.png
    logo-href: https://m154-comp-stats.netlify.app/
  page-footer:
    left: |
      [{{< fa book >}}](https://hardin47.netlify.app/research/)
      <a href ="https://hardin47.netlify.app/resume.pdf" target = "_blank"><i class="fa-solid fa-bookmark"></i></a>
      <a href="mailto:jo.hardin@pomona.edu" target = "_blank"><i class="fa-solid fa-at"></i></a>
      <a href="https://scholar.google.com/citations?user=c5Y77poAAAAJ&hl=en" target = "_blank"><i class="fa-brands fa-google-scholar"></i></a>
      <a href="https://www.researchgate.net/scientific-contributions/Johanna-Hardin-9764530" target = "_blank"><i class="fa-brands fa-researchgate"></i></a>    
      <a href="https://github.com/hardin47" target = "_blank"><i class="fa-brands fa-github"></i></a>
      <a href="https://www.linkedin.com/in/jo-hardin-b91a4b55" target = "_blank"><i class="fa-brands fa-linkedin-in"></i></a>
    center:
      - text: |
          <br> © Jo Hardin, 2025 -- <a href = "mailto: jo.hardin@pomona.edu">jo.hardin@pomona.edu</a> -- <a href="https://hardin47.netlify.app/">https://hardin47.netlify.app/</a> <br> <br>
          Math 154 -- Computational Statistics -- Pomona College <br>
license: "CC BY"
format:
  html:
    theme: 
      - cosmo
      - colors.scss



