---
title: "Schedule"
description: |
  Schedule for Math 154, Computational Statistics, Fall 2021
---


```{r echo = FALSE}
library(tidyverse)
library(kableExtra)
library(knitr)
```

Here's your roadmap for the semester!
Each week, follow the following general process:

- Enjoy the readings <i class="fas fa-book-open"></i>  

- Attend class, review slides <i class="fas fa-desktop" target="_blank"></i> for anything you missed on the agenda  

- Complete the assignment (see Sakai messages for HW link)  

- Discuss the reflection questions <i class="fas fa-lightbulb" target="_blank"></i> and ethics considerations <i class="fas fa-balance-scale"></i> with your classmates, mentor, and professor  



```{r echo = FALSE}
schedule <- tribble(
  ~date, ~topic, ~readings, ~questions, ~ethics, ~slides, ~resources,
  "8.31.21", '<a href="posts/2021-08-31-getting-started-with-r-rstudio/">starting with R + RStudio + Git</a>',
  '<a href="posts/2021-08-31-getting-started-with-r-rstudio/#readings"><i class="fas fa-book-open"></i></a>',
  '<a href="posts/2021-08-31-getting-started-with-r-rstudio/#reflection-questions"><i class="fas fa-lightbulb"></i></a>',
  '<a href="posts/2021-08-31-getting-started-with-r-rstudio/#ethics-considerations"><i class="fas fa-balance-scale"></i></a>',
  '<a href="posts/2021-08-31-getting-started-with-r-rstudio/#slides"><i class="fas fa-desktop"></i></a>',
  '<a href="posts/2021-08-31-getting-started-with-r-rstudio/#additional-resources"><i class="fas fa-laptop"></i></a>',
  "9.7.21", "data viz",
  '<a href=""><i class="fas fa-book-open" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-lightbulb" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-balance-scale" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-desktop" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-laptop"></i></a>',
  "9.14.21", "wrangling",
  '<a href=""><i class="fas fa-book-open" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-lightbulb" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-balance-scale" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-desktop" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-laptop"></i></a>',
  "9.21.21", "simulation",
    '<a href=""><i class="fas fa-book-open" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-lightbulb" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-balance-scale" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-desktop" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-laptop"></i></a>',
  "9.28.21", "randomization inference",
    '<a href=""><i class="fas fa-book-open" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-lightbulb" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-balance-scale" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-desktop" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-laptop"></i></a>',
  "10.5.21", "bootstrapping",
    '<a href=""><i class="fas fa-book-open" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-lightbulb" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-balance-scale" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-desktop" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-laptop"></i></a>',
  "10.12.21", "catch-up + exam",
    '<a href=""><i class="fas fa-book-open" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-lightbulb" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-balance-scale" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-desktop" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-laptop"></i></a>',
  "10.14 + 15.21", "Exam 1", "","","","","", 
  "10.19.21", "ethical issues",
    '<a href=""><i class="fas fa-book-open" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-lightbulb" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-balance-scale" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-desktop" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-laptop"></i></a>',
  "10.22.21", "Take home 1", "","","","","",
  "10.26.21", "knn + trees",
  '<a href=""><i class="fas fa-book-open" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-lightbulb" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-balance-scale" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-desktop" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-laptop"></i></a>',
  "10.26.21", "Initial Project Proposal", "","","","","",
  "11.2.21", "bagging + RF",
  '<a href=""><i class="fas fa-book-open" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-lightbulb" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-balance-scale" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-desktop" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-laptop"></i></a>',
  "11.2.21", "Final Project Proposal", "","","","","",
  "11.9.21", "support vector machines",
    '<a href=""><i class="fas fa-book-open" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-lightbulb" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-balance-scale" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-desktop" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-laptop"></i></a>',
  "11.16.21", "clustering",
    '<a href=""><i class="fas fa-book-open" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-lightbulb" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-balance-scale" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-desktop" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-laptop"></i></a>',
  "11.19.21", "Project Update", "","","","","",
  "11.23.21", "fantastic extensions",
    '<a href=""><i class="fas fa-book-open" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-lightbulb" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-balance-scale" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-desktop" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-laptop"></i></a>',
  "11.30.21", "catch-up + exam",
    '<a href=""><i class="fas fa-book-open" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-lightbulb" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-balance-scale" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-desktop" target="_blank"></i></a>',
  '<a href=""><i class="fas fa-laptop"></i></a>',
  "11.30.21", "Take home 2", "","","","","",
  "12.2 + 3.21", "Exam 2", "","","","","",
  "12.10 + 14.21", "Group Presentations", "","","","","",
  "12.14.21", "Final write-up", "","","","","")
```



```{r echo = FALSE}
schedule %>% 
  kbl(escape = FALSE, align = c(rep('l',2), rep('c',5))) %>%
  kable_styling(bootstrap_options = c("striped", "hover")) %>%
  column_spec(4, )
```



