---
title: "10. Random Forests"
description: |
  Many trees make a forest.
author:
  - name: Johanna Hardin
    url: https://m154-comp-stats.netlify.app/  
date: 2021-10-21
citation: false
draft: false
output:
  distill::distill_article:
    self_contained: false
---



## Agenda <i class="fas fa-calendar-alt" target="_blank"></i>

### November 2, 2021

1. Redux - CART
2. bagging process
3. bagging error rate (OOB error)

### November 4, 2021

1. Random Forests
2. Example

## Readings <i class="fas fa-book-open"></i> 

* Class notes: <a href = "http://st47s.com/Math154/Notes/class.html#bagging" target= "_blank">bagging</a>

* Class notes: <a href = "http://st47s.com/Math154/Notes/class.html#rf" target= "_blank">random forests</a>


* Gareth, Witten, Hastie, and Tibshirani (2021), <a href = "https://web.stanford.edu/~hastie/ISLR2/ISLRv2_website.pdf" target = "_blank">bagging & random forests (section 8.2) </a> Introduction to Statistical Learning.


* Max Kuhn and Julia Silge (2021), <a href = "https://www.tmwr.org/" target = "_blank">Tidy Modeling with R</a>

## Reflection questions <i class="fas fa-lightbulb"></i>

* How does bagging improve on a single tree?  How does tuning `mtry` improve on a single tree?

* How do Random Forests make predictions on test data?

* Can Random Forests be used for both classification and regression or only one of the two tasks?

* Can you use categorical / character predictors with Random Forests?

* How are `mtry` and the number of trees chosen?

* How do the bias and variance change for different values of `mtry` and number of trees?

* What are the advantages of the Random Forests algorithm?

* What are the disadvantages of the Random Forest algorithm?

## Ethics considerations <i class="fas fa-balance-scale"></i> 

* What type of feature engineering is required for Random Forests?

* Do Random Forests produce a closed form "model" that can be written down or visualized and handed to a client?

* If the model produces near perfect predictions on the test data, what are some potential concerns about putting that model into production?

## Slides <i class="fas fa-desktop"></i> 


* <a href = "https://m154-comp-stats.netlify.app/slides/2021-11-02-rf" target = "_blank">In class slides - bagging & random forests</a> for 11/2/21 and 11/4/21.

* From last week: <a href = "https://m154-comp-stats.netlify.app/slides/Math154_WU13_knn.pdf" target = "_blank">WU13 - k-NN</a>

* <a href = "https://m154-comp-stats.netlify.app/slides/Math154_WU15_rd.pdf" target = "_blank">WU15 - random forests</a>

## Additional Resources <i class="fas fa-laptop"></i> 

* <a href = "http://www.wired.com/2008/06/pb-theory/" target = "_blank">The end of science (???)</a> "The End of Theory: The Data Deluge Makes the Scientific Method Obsolete", *Science*, June 23, 2008.

* <a href = "http://simplystatistics.org/2014/05/22/10-things-statistics-taught-us-about-big-data-analysis/" target = "_blank">Maybe not so fast.</a> "10 things statistics taught us about big data analysis", Jeff Leek, May 22, 2014.


